language: python

python:
  - "3.7"

install:
  - pip install -r requirements-dev.txt
  - python -c "import nltk;
      nltk.download('punkt');
      nltk.download('averaged_perceptron_tagger');
      nltk.download('maxent_ne_chunker');
      nltk.download('words');
      nltk.download('wordnet');"

script:
  - coverage run -m unittest discover

after_success:
  - codecov